INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES
('Marcos Andre da Silva', 'Conta de pessoa fisica', 1000.00, TRUE),
('Rebeca Andrade', 'Conta de pessoa fisica', 500.00, TRUE),
('Bruno Henrique', 'Conta de pessoa fisica', 5000.00, false),
('João de Souza Dias', 'Conta de pessoa fisica', 0.00, TRUE),
('Artemis das Costa Ribeiro', 'Conta de pessoa fisica', 1500.00, TRUE),
('Pedro Costa', 'Conta de pessoa fisica', 3500.00, false),
('Joana DArc', 'Conta de pessoa fisica', 100.00, TRUE),
('Ana Luiza Ribeiro', 'Conta de pessoa fisica', 100.00, TRUE),
('Maria de Nazare Souza', 'Conta de pessoa fisica', 0.00, TRUE),
('Paulo da Silva e Silva', 'Conta de pessoa fisica', 0.00, TRUE),
('Anita Queiroz Gonçalves', 'Conta de pessoa fisica', 0.00, TRUE),
('Tereza Cristina ', 'Conta de pessoa fisica', 0.00, false),
('Luciola Queiroz', 'Conta de pessoa fisica', 0.00, false),
('Pedro Costa', 'Conta de pessoa fisica', 0.00, TRUE),
('Zdeněk Jelínek', 'Conta de pessoa fisica', 0.00, TRUE),
('Anne Madsen', 'Conta de pessoa fisica', 0.00, TRUE),
('Olivia Knutsen', 'Conta de pessoa fisica', 0.00, TRUE),
('Logan Williams', 'Conta de pessoa fisica', 0.00, TRUE),
('Anne Madsen', 'Conta de pessoa fisica', 0.00, TRUE),
('Olivia Knutsen', 'Conta de pessoa fisica', 0.00, TRUE),
('Logan Williams', 'Conta de pessoa fisica', 0.00, TRUE),
('Kathleen Harris', 'Conta de pessoa fisica', 0.00, TRUE),
('Reinis Volkovs', 'Conta de pessoa fisica', 0.00, TRUE),
('Greta Rinaldini', 'Conta de pessoa fisica', 0.00, false),
('Saga Hauge', 'Conta de pessoa fisica', 0.00, TRUE),
('Søs Jørgensen', 'Conta de pessoa fisica', 0.00, TRUE),
('Aurora Contreras', 'Conta de pessoa fisica', 0.00, false),
('Sofia Cools', 'Conta de pessoa fisica', 0.00, TRUE),
('Linnéa Hassan', 'Conta de pessoa fisica', 0.00, TRUE),
('Léa François', 'Conta de pessoa fisica', 0.00, TRUE),
('María Victoria García', 'Conta de pessoa fisica', 0.00, TRUE),
('Hazel Casey', 'Conta de pessoa fisica', 0.00, FALSE);
